context("estimatePeformanceMetrics")
test_that("test='estimatePerformanceMetrics' returns informative messages", {
  data( sb )
  expect_error( estimatePerformanceMetrics( 1:10 ) )
  expect_error( estimatePerformanceMetrics( sb ) )
  sb <- addDefaultMetrics( sb )
  expect_s4_class( estimatePerformanceMetrics( sb ), "DataFrame" )
  tidyRes1 <- estimatePerformanceMetrics( sb, tidy=TRUE )
  expect_s3_class( tidyRes1, "data.frame" )
  sb <- estimatePerformanceMetrics( sb, addColData=TRUE )
  tidyRes2 <- tidyUpMetrics( sb )
  expect_identical( tidyRes1, tidyRes2 )
  expect_message( estimatePerformanceMetrics(sb) )
} )
